apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: northstar-traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  targetNamespace: kube-system
  createNamespace: false
  valuesContent: |-
    deployment:
      replicas: 1
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik
    providers:
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
    service:
      type: LoadBalancer
      ports:
        web:
          port: 8000
          exposedPort: 80
          expose:
            default: true
        websecure:
          port: 8443
          exposedPort: 443
          expose:
            default: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
