apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  namespace: northstar-dev
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: northstar
data:
  ENVIRONMENT: development
  LOG_LEVEL: INFO
  REDIS_URL: redis://redis:6379/0
