apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: northstar-dev
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: northstar
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: checkout

  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
