apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: northstar-dev
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: northstar
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
